version: '3.9'
services:
  node:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: connex-ai-backend
    ports:
      - '5000:5000'
    env_file:
      - ./api/.env  

  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: connex-ai-frontend
    ports:
      - '3000:3000'
    stdin_open: true
    
